Prevent inclusion of system <getopt.h>
This avoids the inclusion of he systems getopt.h header file as we
redefine symbols that may have been defined differently on some systems
(Cygwin/Mingw in that case).

This fixes building on Cygwin resolving the following errors:

In file included from ../include/hex.h:36:0,
                 from file.c:19:
../include/hgetopt.h:41:14: error: 'optarg' redeclared without dllimport attribute: previous dllimport ignored [-Werror=attributes]
 extern char *optarg;
              ^~~~~~
../include/hgetopt.h:55:12: error: 'optind' redeclared without dllimport attribute: previous dllimport ignored [-Werror=attributes]
 extern int optind;
            ^~~~~~
../include/hgetopt.h:60:12: error: 'opterr' redeclared without dllimport attribute: previous dllimport ignored [-Werror=attributes]
 extern int opterr;
            ^~~~~~
../include/hgetopt.h:64:12: error: 'optopt' redeclared without dllimport attribute: previous dllimport ignored [-Werror=attributes]
 extern int optopt;
            ^~~~~~

Signed-off-by: Konrad Gräfe <konradgraefe@aol.com>